# Generated by Django 5.1.1 on 2024-11-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durack_cards', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
