# Generated by Django 5.1.1 on 2024-11-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durack_cards', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name_room',
            field=models.CharField(default='default_room', max_length=100),
        ),
    ]
