# Generated by Django 5.1.1 on 2024-11-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durack_cards', '0004_player_name_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='trum',
            new_name='trun',
        ),
    ]
