# Generated by Django 5.1.1 on 2024-11-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durack_cards', '0005_rename_trum_player_trun'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_order',
            field=models.JSONField(default=list),
        ),
    ]
