# Generated by Django 5.1.1 on 2024-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durack_cards', '0006_room_player_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
