# Generated by Django 5.1.1 on 2024-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durack_cards', '0007_player_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='attack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='deck',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='translation',
            field=models.BooleanField(default=False),
        ),
    ]
