# Generated by Django 5.1.1 on 2024-12-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('durack_cards', '0008_room_attack_room_deck_room_draw_room_fake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
