# Generated by Django 5.1.1 on 2024-12-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('durack_cards', '0009_room_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='fake',
            new_name='cheater',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='translation',
            new_name='transfer',
        ),
    ]
