# Generated by Django 5.1.1 on 2025-01-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participants', models.PositiveIntegerField(default=2)),
                ('deck', models.PositiveIntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('isPrivate', models.BooleanField(default=False)),
                ('password', models.PositiveIntegerField(default=0)),
                ('hew', models.BooleanField(default=False)),
                ('push', models.BooleanField(default=False)),
                ('cards', models.JSONField(default=list)),
                ('player_order', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trun', models.IntegerField()),
                ('redy', models.BooleanField()),
                ('name_room', models.CharField(default='default_room', max_length=100)),
                ('player_id', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='seka_cards.room')),
            ],
        ),
    ]
