# Generated by Django 5.1.1 on 2025-01-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seka_cards', '0002_room_banck_room_bet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='banck',
            new_name='bank',
        ),
    ]
