# Generated by Django 5.1.1 on 2025-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seka_cards', '0003_rename_banck_room_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bleackMove',
            field=models.BooleanField(default=False),
        ),
    ]
