# Generated by Django 5.1.1 on 2025-03-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seka_cards', '0004_room_bleackmove'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_cards_order',
            field=models.JSONField(default=list),
        ),
    ]
