# Generated by Django 5.1.1 on 2025-04-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, to='players.player'),
        ),
    ]
