# Generated by Django 5.1.1 on 2025-06-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, symmetrical=False, to='players.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ] 