# Generated by Django 5.2.3 on 2025-07-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_friends_alter_player_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(default='default_avatar.png', max_length=255),
        ),
    ]
